# Generated by Django 5.2.5 on 2025-08-09 15:31

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.CharField(default=events.models.generate_sponsor_id, max_length=36, primary_key=True, serialize=False)),
                ('sponsor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'sponsors',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(default=events.models.generate_event_id, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('college', models.ForeignKey(db_column='college_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='colleges.college')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='accounts.adminprofile', to_field='admin_id')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='events.event')),
                ('sponsor', models.ForeignKey(db_column='sponsor_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='events.sponsor')),
            ],
            options={
                'db_table': 'event_sponsors',
                'unique_together': {('event', 'sponsor')},
            },
        ),
    ]
