# Generated by Django 5.2.5 on 2025-08-17 11:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(default=accounts.models.generate_user_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('profile_info', models.CharField(blank=True, max_length=50, null=True)),
                ('preferences', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
