# Generated by Django 5.2.5 on 2025-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_name_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pasword',
            field=models.CharField(default='1234', max_length=128),
        ),
    ]
