# Generated by Django 5.2.5 on 2025-08-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_pasword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pasword',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
