# Generated by Django 5.2.5 on 2025-08-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_pasword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pasword',
            field=models.CharField(max_length=128),
        ),
    ]
