# Generated by Django 5.2.5 on 2025-08-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_pasword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pasword',
            new_name='password',
        ),
    ]
