# Generated by Django 5.2.5 on 2025-08-09 15:32

import analytics.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.CharField(default=analytics.models.generate_analytics_id, max_length=20, primary_key=True, serialize=False)),
                ('engagement_score', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('popular_event', models.CharField(blank=True, max_length=20)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='events.event')),
            ],
            options={
                'db_table': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics', models.ForeignKey(db_column='analytics_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='analytics.analytics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_users',
                'unique_together': {('analytics', 'user')},
            },
        ),
        migrations.AddField(
            model_name='analytics',
            name='users',
            field=models.ManyToManyField(related_name='analytics_items', through='analytics.AnalyticsUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
