# Generated by Django 5.2.5 on 2025-08-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_pasword_userprofile_password'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='users',
            field=models.ManyToManyField(related_name='analytics_items', through='analytics.AnalyticsUser', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='analyticsuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_links', to='accounts.userprofile'),
        ),
    ]
