# Generated by Django 5.2.5 on 2025-08-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analytics_users_alter_analyticsuser_user'),
    ]

    operations = [
    ]
