# Generated by Django 5.2.5 on 2025-08-09 15:32

import django.db.models.deletion
import ugc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(default=ugc.models.generate_review_id, max_length=20, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='UGC',
            fields=[
                ('ugc_id', models.CharField(default=ugc.models.generate_ugc_id, max_length=20, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('text', 'Text')], max_length=30)),
                ('content_data', models.CharField(blank=True, max_length=150)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='ugc_items', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugc_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ugc',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.CharField(default=ugc.models.generate_photo_id, max_length=20, primary_key=True, serialize=False)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
                ('ugc', models.ForeignKey(db_column='ugc_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ugc.ugc')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
