# Generated by Django 5.2.5 on 2025-08-09 15:31

import django.db.models.deletion
import registrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(default=registrations.models.generate_invoice_id, max_length=20, primary_key=True, serialize=False)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(default=registrations.models.generate_payment_id, max_length=20, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('gateway', models.CharField(blank=True, max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='registrations.invoice')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.CharField(default=registrations.models.generate_registration_id, max_length=20, primary_key=True, serialize=False)),
                ('payment_status', models.CharField(blank=True, max_length=30)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registrations',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='registrations.registration'),
        ),
    ]
